leftnav:
- identifier: 8834e852-de1c-40d9-8449-38c96c780c01
  name: The Fundamentals
  pageRef: /external-resources/the-fundamentals_8834e852-de1c-40d9-8449-38c96c780c01
  weight: 10
- identifier: 5a8b1824-a77b-4c77-b1de-3b80b12e8cb1
  name: Analysis and Application
  pageRef: /external-resources/analysis-and-application_5a8b1824-a77b-4c77-b1de-3b80b12e8cb1
  weight: 20
- identifier: eeedc673-47ac-4cef-a3fb-e1e2b25d70f9
  name: Population Genetics and Human Traits
  pageRef: /external-resources/population-genetics-and-human-traits
  weight: 30
